language: node_js
node_js:
  - "6.9"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g @angular/cli

branches:
  only:
    - develop
    - /^greenkeeper/.*$/
    - /^feature/.*$/
    - /^release/.*$/
    - /^hotfix/.*$/

before_script:

script:
  - ng lint
  - ng test -sr
  - ng test -sr -cc

after_success:
  - ./node_modules/.bin/codecov

notifications:
  email:
    on_failure: change
    on_success: change
